### PR TITLE
Hospital Website

### PR DESCRIPTION
**Pull request by rajathnair**

### CODE REVIEW

**Comment by hrshammo** [comment]
Hay! Thanks For the PR .. Just upload in on Web folder ...

**Comment by rajathnair** [comment]
> Hay! Thanks For the PR .. Just upload in on Web folder ...

But, How to do that ? Can u just guide me ?

**Comment by hrshammo** [comment]
Yes...There is a folder named "Web" upload your project into that

**Comment by rajathnair** [comment]
okay, I will close this and will re upload the file in the web folder

**Pull request closed without merging**
